name: Build and Sign Nextcloud App Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'manuelbernalcarvajal'
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          path: pwa_suite

      - name: Empaquetar y firmar la App
        env:
          PRIVATE_KEY: ${{ secrets.NC_PRIVATE_KEY }}
        run: |
          mkdir -p build/artifacts
          
          # 1. Empaquetar la carpeta excluyendo archivos de Git y workflows
          tar --exclude='pwa_suite/.git*' --exclude='pwa_suite/.github' -czf build/artifacts/pwa_suite.tar.gz pwa_suite
          
          # 2. Guardar temporalmente la clave privada para firmar
          echo "$PRIVATE_KEY" > key.pem
          
          # 3. Firmar el archivo comprimido y guardar la firma en un archivo de texto
          openssl dgst -sha512 -sign key.pem build/artifacts/pwa_suite.tar.gz | openssl base64 > build/artifacts/pwa_suite.sig
          
          # 4. Eliminar la clave temporal por seguridad
          rm -f key.pem

      - name: Publicar Release en GitHub
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build/artifacts/pwa_suite.tar.gz
            build/artifacts/pwa_suite.sig
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
